### ISSUE TITLE
Allow certain html elements in notes, markdown?

### ISSUE THREAD

**Issue by elistone** [elistone/chrome-deployment-windows#1]
**Is your feature request related to a problem? Please describe.**
When adding in notes it would be good to be able to use some kind of html in the text to highlight things or put into bullet points.

**Describe the solution you'd like**
Have a nice easy way to add markup to strings, can use raw html tags or markup.

Maybe something like this: https://github.com/rexxars/react-markdown would work?

Otherwise just getting `<ul><ol><i><b><a>` tags would be a good start.

**Tasks**

- [x] Allow html or markdown tags
- [x] Render on page banner
- [x] Render in popup
- [x] Render on options page

**Comment by elistone** [comment]
This feature has now been implemented.
