### ISSUE TITLE
Help page

### ISSUE THREAD

**Issue by elistone** [elistone/chrome-deployment-windows#13]
**Is your feature request related to a problem? Please describe.**
A help page explaining all the options and setting from inside the application would be good.
So you don't need to look at the readme of this project everything is just contained

**Describe the solution you'd like**
A new page to be created in the options explaining how to use the extension.
Would be good to have this file be in markdown, that is then loaded into the options page. So we can update the information in one place and have it display in the extension and on the repo.

**Tasks**

- [x] Create help / how to use .md
- [x] Add new page to options
- [x] Have it load and render the help / how to use .md

**Comment by elistone** [comment]
This feature has now been implemented see #28 for more details.
