### ISSUE TITLE
Setup cypress testing

### ISSUE THREAD

**Issue by elistone** [elistone/chrome-deployment-windows#15]
**Is your feature request related to a problem? Please describe.**
Implement cypress testing. This would try to make sure that any changes to the backend code do not break the front end.

**Describe the solution you'd like**
Cypress testing is implanted with GitHub actions running to test on new commits.

**Tasks**
- [x] Add cypress to the project
- [x] Setup to work with browser extensions
- [x] Add some tests
- [x] Setup GitHub actions

See: https://medium.com/@knoldus/how-to-load-chrome-extension-in-cypress-io-e313d3c68988

**Comment by elistone** [comment]
This feature has now been implemented see #24 for more details.
