### ISSUE TITLE
Better validation of JSON

### ISSUE THREAD

**Issue by elistone** [elistone/chrome-deployment-windows#3]
We should be able to validate on save if the JSON is validate and contains everything we expected.
If not notify what is wrong and why.

**Is your feature request related to a problem? Please describe.**
Currently you can simply write whatever you want in the JSON settings, does not matter if things are correct or if extra strings are added.

**Describe the solution you'd like**
When pressing save you should be notified if things are incorrect or invalid.

**tasks**

- [x] Implement validation on save
- [x] Notify what is wrong
- [ ] Suggest possible solutions (optional)

**Comment by elistone** [comment]
Have added top level key testing, this is a good start for validation.
