### ISSUE TITLE
Improve the Manifest and App icons.

### ISSUE THREAD

**Issue by elistone** [elistone/chrome-deployment-windows#5]
The icons still could do with some work, I like the look but they still feel very small.

**Is your feature request related to a problem? Please describe.**
The icon for the project as well as the icons for deployment status (the popup icon) could be improved to give a better quick look.

**Describe the solution you'd like**
Create new icons designs and at a better resolution. 

Use one of the following templates:
Square: https://developer.chrome.com/webstore/images/128-square.png
Circle: https://developer.chrome.com/webstore/images/128-circle.png
irregular: https://developer.chrome.com/webstore/images/128-irregular.png

More information found here:
https://developer.chrome.com/webstore/images#icons
https://developer.chrome.com/apps/manifest/icons

**Tasks**
- [ ] Create new base icon
- [ ] Create new deployment open icon
- [ ] Create new deployment closed icon
- [ ] Make sure we have the correct sizes: 128px | 48px | 32px | 16px
