### ISSUE TITLE
Remove dist folder from repo

### ISSUE THREAD

**Issue by elistone** [elistone/chrome-deployment-windows#7]
**Is your feature request related to a problem? Please describe.**
The dist folder does not need to be inside the repo, the contents of the folder could be put into other folders.

**Describe the solution you'd like**
The ability to run`npm run build` and have all files/folders are copied to the correct location, creating the dist folder.

**Tasks**
- [x] Move non generated files over to other folders
- [x] Remove the dist folder
- [x] Update build script to combine everything back together

**Comment by elistone** [comment]
Implemented these changes.
