### ISSUE TITLE
Ability to just show messages

### ISSUE THREAD

**Issue by elistone** [elistone/chrome-deployment-windows#8]
It would be nice to have an option to just show a message e.g. the notes without the deployment information.

**Is your feature request related to a problem? Please describe.**
Currently you can only add a notice if it is about a deployment window, it would be nice have the ability to add just notes to a project. This could be to do things like explain specific workflows, or maybe warnings about certain files.

**Describe the solution you'd like**
A flag to state that a deployment window is not required and that would then just display notes.

**Tasks**

- [x] Create a notes only flag
- [x] Create notes only design (maybe use warning colours)
- [x] Update banner to display only notes
- [x] Update popup to display only notes
- [x] Update settings pages to state if notes only
- [x] Update readme to explain feature

**Comment by elistone** [comment]
This feature has now been implemented see PR #19 for more details.
