### ISSUE TITLE
Url validation should not always be case sensitive

### ISSUE THREAD

**Issue by elistone** [elistone/chrome-deployment-windows#9]
It looks like the urls are case sensitive, we should enable a flag for case sensitive or just make case not import.

**Is your feature request related to a problem? Please describe.**
Found out that the checking for valid url pattern is case sensitive, this should not be the case and we be good if the url case did not matter.

**Describe the solution you'd like**
Two options:

1. Enforce all urls to be case insensitive.
1. Add a flag to enable case sensitive but have it disabled by default.

**Tasks**
- [x] Enforce all urls pattern matching to be case insensitive
- [x] (optional) add in a flag that disables the case insensitive setting
- [x] Update the readme to explain this changes

**Comment by elistone** [comment]
This feature has now been implemented see PR #18 for more details.
